# Copyright 2026 Rafael Martins Alves -- Apache-2.0

"""Coverage-focused tests for ``lub.connectors.bridge.session.SessionManager``.

Targets the SessionManager facade + InMemorySessionStore happy paths and
the lifecycle policy (TTL expiry, resolution, escalation, metrics) so
the audit/retention numbers the platform reports come from a tested
code path.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta

import pytest

from lub.connectors.bridge.session import (
    Channel,
    InMemorySessionStore,
    Message,
    MessageRole,
    Session,
    SessionManager,
    SessionMetrics,
    SessionNotFoundError,
)

UTC = UTC


# ---------------------------------------------------------------------------
# Construction
# ---------------------------------------------------------------------------


class TestConstruction:
    def test_default_ttl_24h(self) -> None:
        m = SessionManager(InMemorySessionStore())
        assert m._ttl == timedelta(hours=24)

    def test_zero_ttl_raises(self) -> None:
        with pytest.raises(ValueError, match="ttl must be positive"):
            SessionManager(InMemorySessionStore(), ttl=timedelta(seconds=0))

    def test_negative_ttl_raises(self) -> None:
        with pytest.raises(ValueError):
            SessionManager(InMemorySessionStore(), ttl=timedelta(seconds=-1))

    def test_store_property(self) -> None:
        store = InMemorySessionStore()
        m = SessionManager(store)
        assert m.store is store


# ---------------------------------------------------------------------------
# Start / get / append
# ---------------------------------------------------------------------------


class TestSessionLifecycle:
    def setup_method(self) -> None:
        self.m = SessionManager(InMemorySessionStore())

    def test_start_creates_session(self) -> None:
        s = self.m.start("c-1", Channel.WHATSAPP)
        assert s.customer_id == "c-1"
        assert s.channel == Channel.WHATSAPP
        assert s.session_id  # autogenerated UUID

    def test_start_with_explicit_session_id(self) -> None:
        s = self.m.start("c-1", Channel.WEB, session_id="my-id")
        assert s.session_id == "my-id"

    def test_start_with_system_prompt_appends_message(self) -> None:
        s = self.m.start("c-1", Channel.MOBILE_APP, system_prompt="Voce e o Bridge")
        assert len(s.messages) == 1
        assert s.messages[0].role == MessageRole.SYSTEM
        assert s.messages[0].content == "Voce e o Bridge"

    def test_start_with_metadata(self) -> None:
        s = self.m.start("c-1", Channel.MOBILE_APP, metadata={"region": "SP"})
        assert s.metadata == {"region": "SP"}

    def test_get_returns_started_session(self) -> None:
        s = self.m.start("c-1", Channel.MOBILE_APP)
        assert self.m.get(s.session_id).session_id == s.session_id

    def test_get_unknown_raises(self) -> None:
        with pytest.raises(SessionNotFoundError):
            self.m.get("does-not-exist")

    def test_append_adds_to_messages(self) -> None:
        s = self.m.start("c-1", Channel.MOBILE_APP)
        self.m.append(s.session_id, MessageRole.USER, "qual saldo?")
        self.m.append(s.session_id, MessageRole.ASSISTANT, "R$ 100")
        out = self.m.get(s.session_id)
        assert len(out.messages) == 2

    def test_append_to_resolved_raises(self) -> None:
        s = self.m.start("c-1", Channel.MOBILE_APP)
        self.m.resolve(s.session_id)
        with pytest.raises(ValueError, match="closed session"):
            self.m.append(s.session_id, MessageRole.USER, "another")

    def test_append_to_escalated_raises(self) -> None:
        s = self.m.start("c-1", Channel.MOBILE_APP)
        self.m.escalate(s.session_id, "test")
        with pytest.raises(ValueError, match="closed session"):
            self.m.append(s.session_id, MessageRole.USER, "another")


# ---------------------------------------------------------------------------
# Resolve / escalate
# ---------------------------------------------------------------------------


class TestResolveEscalate:
    def setup_method(self) -> None:
        self.m = SessionManager(InMemorySessionStore())

    def test_resolve_marks_session(self) -> None:
        s = self.m.start("c-1", Channel.MOBILE_APP)
        self.m.resolve(s.session_id)
        assert self.m.get(s.session_id).resolved is True

    def test_escalate_marks_session_with_reason(self) -> None:
        s = self.m.start("c-1", Channel.MOBILE_APP)
        self.m.escalate(s.session_id, "low_confidence")
        out = self.m.get(s.session_id)
        assert out.escalated is True
        assert out.metadata["escalation_reason"] == "low_confidence"


# ---------------------------------------------------------------------------
# Idle TTL expiry
# ---------------------------------------------------------------------------


class TestIdleExpiry:
    def test_idle_session_gets_escalated(self) -> None:
        m = SessionManager(InMemorySessionStore(), ttl=timedelta(seconds=60))
        s = m.start("c-1", Channel.MOBILE_APP)
        # Force a stale last_active_at
        stored = m.get(s.session_id)
        stored.last_active_at = datetime.now(UTC) - timedelta(hours=1)
        m._store.put(stored)

        expired = m.expire_idle()
        assert s.session_id in expired
        assert m.get(s.session_id).escalated is True

    def test_fresh_session_not_expired(self) -> None:
        m = SessionManager(InMemorySessionStore(), ttl=timedelta(hours=1))
        s = m.start("c-1", Channel.MOBILE_APP)
        expired = m.expire_idle()
        assert s.session_id not in expired

    def test_resolved_sessions_skipped(self) -> None:
        m = SessionManager(InMemorySessionStore(), ttl=timedelta(seconds=10))
        s = m.start("c-1", Channel.MOBILE_APP)
        m.resolve(s.session_id)
        # Even with stale timestamp, resolved sessions are skipped
        stored = m.get(s.session_id)
        stored.last_active_at = datetime.now(UTC) - timedelta(hours=1)
        m._store.put(stored)
        expired = m.expire_idle()
        assert s.session_id not in expired


# ---------------------------------------------------------------------------
# History + metrics
# ---------------------------------------------------------------------------


class TestHistoryAndMetrics:
    def test_history_returns_chat_format(self) -> None:
        m = SessionManager(InMemorySessionStore())
        s = m.start("c-1", Channel.MOBILE_APP)
        m.append(s.session_id, MessageRole.USER, "hi")
        m.append(s.session_id, MessageRole.ASSISTANT, "hello")
        h = m.history(s.session_id)
        assert h == [
            {"role": "user", "content": "hi"},
            {"role": "assistant", "content": "hello"},
        ]

    def test_metrics_empty_store(self) -> None:
        m = SessionManager(InMemorySessionStore())
        metrics = m.metrics()
        assert isinstance(metrics, SessionMetrics)
        assert metrics.total == 0
        assert metrics.retention_rate == 0.0

    def test_metrics_resolved_counts(self) -> None:
        m = SessionManager(InMemorySessionStore())
        s1 = m.start("c-1", Channel.MOBILE_APP)
        s2 = m.start("c-2", Channel.WHATSAPP)
        s3 = m.start("c-3", Channel.WEB)
        m.resolve(s1.session_id)
        m.resolve(s2.session_id)
        m.escalate(s3.session_id, "low_conf")
        metrics = m.metrics()
        assert metrics.total == 3
        assert metrics.resolved == 2
        assert metrics.escalated == 1
        # 2 resolved out of 3 closed = 66.7%
        assert metrics.retention_rate == pytest.approx(2 / 3, abs=0.01)

    def test_metrics_by_channel_breakdown(self) -> None:
        m = SessionManager(InMemorySessionStore())
        m.start("c-1", Channel.MOBILE_APP)
        m.start("c-2", Channel.MOBILE_APP)
        m.start("c-3", Channel.WHATSAPP)
        metrics = m.metrics()
        assert metrics.by_channel == {"mobile_app": 2, "whatsapp": 1}

    def test_metrics_open_sessions_counted(self) -> None:
        m = SessionManager(InMemorySessionStore())
        m.start("c-1", Channel.MOBILE_APP)
        m.start("c-2", Channel.WEB)
        metrics = m.metrics()
        assert metrics.open_sessions == 2


# ---------------------------------------------------------------------------
# InMemorySessionStore directly (the protocol contract)
# ---------------------------------------------------------------------------


class TestInMemoryStore:
    def test_put_and_get(self) -> None:
        store = InMemorySessionStore()
        s = Session(session_id="x", customer_id="c-1", channel=Channel.MOBILE_APP)
        store.put(s)
        assert store.get("x") is not None

    def test_get_missing_raises(self) -> None:
        store = InMemorySessionStore()
        with pytest.raises(SessionNotFoundError):
            store.get("nope")

    def test_delete_present(self) -> None:
        store = InMemorySessionStore()
        s = Session(session_id="x", customer_id="c-1", channel=Channel.MOBILE_APP)
        store.put(s)
        store.delete("x")
        with pytest.raises(SessionNotFoundError):
            store.get("x")

    def test_delete_missing_silent(self) -> None:
        # Per docstring: 'silently ignore an unknown id' (LGPD right-to-erasure path).
        InMemorySessionStore().delete("nope")  # should not raise

    def test_list_for_customer_filters(self) -> None:
        store = InMemorySessionStore()
        store.put(Session(session_id="a", customer_id="c-1", channel=Channel.MOBILE_APP))
        store.put(Session(session_id="b", customer_id="c-1", channel=Channel.WEB))
        store.put(Session(session_id="c", customer_id="c-2", channel=Channel.MOBILE_APP))
        c1 = store.list_for_customer("c-1")
        assert len(c1) == 2
        assert all(s.customer_id == "c-1" for s in c1)

    def test_all_sessions(self) -> None:
        store = InMemorySessionStore()
        store.put(Session(session_id="a", customer_id="c-1", channel=Channel.MOBILE_APP))
        store.put(Session(session_id="b", customer_id="c-2", channel=Channel.WEB))
        assert len(store.all_sessions()) == 2


# ---------------------------------------------------------------------------
# Session + Message dataclass round-trips
# ---------------------------------------------------------------------------


class TestSerialization:
    def test_session_to_dict_round_trip(self) -> None:
        s = Session(session_id="x", customer_id="c-1", channel=Channel.MOBILE_APP)
        s.append(Message(role=MessageRole.USER, content="hi"))
        s.append(Message(role=MessageRole.ASSISTANT, content="hello"))
        d = s.to_dict()
        s2 = Session.from_dict(d)
        assert s2.session_id == s.session_id
        assert s2.customer_id == s.customer_id
        assert len(s2.messages) == 2

    def test_message_to_dict_round_trip(self) -> None:
        m = Message(role=MessageRole.USER, content="hi", metadata={"channel": "x"})
        d = m.to_dict()
        m2 = Message.from_dict(d)
        assert m2.role == m.role
        assert m2.content == m.content
        assert m2.metadata == m.metadata

    def test_session_duration(self) -> None:
        s = Session(
            session_id="x",
            customer_id="c-1",
            channel=Channel.MOBILE_APP,
            started_at=datetime(2026, 1, 1, 12, 0, tzinfo=UTC),
            last_active_at=datetime(2026, 1, 1, 12, 5, tzinfo=UTC),
        )
        assert s.duration == timedelta(minutes=5)
